package Modelo;
// Generated 19/05/2016 10:58:30 PM by Hibernate Tools 4.3.1



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private ContactoId id;
     private Usuario usuario;
     private String informacion;

    public Contacto() {
    }

	
    public Contacto(ContactoId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Contacto(ContactoId id, Usuario usuario, String informacion) {
       this.id = id;
       this.usuario = usuario;
       this.informacion = informacion;
    }
   
    public ContactoId getId() {
        return this.id;
    }
    
    public void setId(ContactoId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getInformacion() {
        return this.informacion;
    }
    
    public void setInformacion(String informacion) {
        this.informacion = informacion;
    }




}


