package Modelo;
// Generated 19/05/2016 10:58:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private int idprestamo;
     private Objeto objeto;
     private Usuario usuarioByIdconsumidor;
     private Usuario usuarioByIdprestador;
     private Date fechaprestamo;
     private Integer calificacionprestador;
     private Integer calificaconsumidor;
     private String opinionsobreprestador;
     private String opinionsobreconsumidor;
     private Integer tiemposolicitado;
     private String medida;

    public Prestamo() {
    }

	
    public Prestamo(int idprestamo, Objeto objeto, Usuario usuarioByIdconsumidor, Usuario usuarioByIdprestador) {
        this.idprestamo = idprestamo;
        this.objeto = objeto;
        this.usuarioByIdconsumidor = usuarioByIdconsumidor;
        this.usuarioByIdprestador = usuarioByIdprestador;
    }
    public Prestamo(int idprestamo, Objeto objeto, Usuario usuarioByIdconsumidor, Usuario usuarioByIdprestador, Date fechaprestamo, Integer calificacionprestador, Integer calificaconsumidor, String opinionsobreprestador, String opinionsobreconsumidor, Integer tiemposolicitado, String medida) {
       this.idprestamo = idprestamo;
       this.objeto = objeto;
       this.usuarioByIdconsumidor = usuarioByIdconsumidor;
       this.usuarioByIdprestador = usuarioByIdprestador;
       this.fechaprestamo = fechaprestamo;
       this.calificacionprestador = calificacionprestador;
       this.calificaconsumidor = calificaconsumidor;
       this.opinionsobreprestador = opinionsobreprestador;
       this.opinionsobreconsumidor = opinionsobreconsumidor;
       this.tiemposolicitado = tiemposolicitado;
       this.medida = medida;
    }
   
    public int getIdprestamo() {
        return this.idprestamo;
    }
    
    public void setIdprestamo(int idprestamo) {
        this.idprestamo = idprestamo;
    }
    public Objeto getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(Objeto objeto) {
        this.objeto = objeto;
    }
    public Usuario getUsuarioByIdconsumidor() {
        return this.usuarioByIdconsumidor;
    }
    
    public void setUsuarioByIdconsumidor(Usuario usuarioByIdconsumidor) {
        this.usuarioByIdconsumidor = usuarioByIdconsumidor;
    }
    public Usuario getUsuarioByIdprestador() {
        return this.usuarioByIdprestador;
    }
    
    public void setUsuarioByIdprestador(Usuario usuarioByIdprestador) {
        this.usuarioByIdprestador = usuarioByIdprestador;
    }
    public Date getFechaprestamo() {
        return this.fechaprestamo;
    }
    
    public void setFechaprestamo(Date fechaprestamo) {
        this.fechaprestamo = fechaprestamo;
    }
    public Integer getCalificacionprestador() {
        return this.calificacionprestador;
    }
    
    public void setCalificacionprestador(Integer calificacionprestador) {
        this.calificacionprestador = calificacionprestador;
    }
    public Integer getCalificaconsumidor() {
        return this.calificaconsumidor;
    }
    
    public void setCalificaconsumidor(Integer calificaconsumidor) {
        this.calificaconsumidor = calificaconsumidor;
    }
    public String getOpinionsobreprestador() {
        return this.opinionsobreprestador;
    }
    
    public void setOpinionsobreprestador(String opinionsobreprestador) {
        this.opinionsobreprestador = opinionsobreprestador;
    }
    public String getOpinionsobreconsumidor() {
        return this.opinionsobreconsumidor;
    }
    
    public void setOpinionsobreconsumidor(String opinionsobreconsumidor) {
        this.opinionsobreconsumidor = opinionsobreconsumidor;
    }
    public Integer getTiemposolicitado() {
        return this.tiemposolicitado;
    }
    
    public void setTiemposolicitado(Integer tiemposolicitado) {
        this.tiemposolicitado = tiemposolicitado;
    }
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }

    @Override
    public int hashCode() {
        int num= (objeto.hashCode() * 17) * 31;
        num = (num + usuarioByIdconsumidor.hashCode()) * 17;
        num = (num + usuarioByIdprestador.hashCode()) * 17; 
        return num; //To change body of generated methods, choose Tools | Templates.
    }
    



}


