package Modelo;
// Generated 19/05/2016 10:58:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombreusuario;
     private String contrasenia;
     private String nombre;
     private String apellidos;
     private String correo;
     

    public Usuario() {
    }

    public Usuario(int idusuario, String nombreusuario, String contrasenia, String nombre, String apellidos, String correo) {
        this.idusuario = idusuario;
        this.nombreusuario = nombreusuario;
        this.contrasenia = contrasenia;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.correo = correo;
    }

    	
    public Usuario(int idusuario, String nombreusuario) {
        this.idusuario = idusuario;
        this.nombreusuario = nombreusuario;
    }
   
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    @Override
    public int hashCode() {
        return (nombreusuario.hashCode() + 17) * 31; //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String toString() {
        return nombreusuario; //To change body of generated methods, choose Tools | Templates.
    }
    



}


